apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: gitops-webhook-token
spec:
  encryptedData:
    webhook-token: AgCE8wuyjEgX5TbyCED1h84kw1uMbAIHRS3IlObWSoQJSggFzWi0KYQgVwJ3A/zAcy0LFRLHqvz6ZvSi9yqKcvOna6ULPBFbwdDpS8ZgkJjQUhF/pwoKqHTDvFj5leSoaBEKl6oSg8bCiUg2rFBIwirwgbqB1V2GApTp/tG84JIkTIb223x5/MbS8+ZXJBteD09Vt4AVzl25oblgJPIgQK+gEKPyvctijw/QAZceR4g1vYMp0turfAA+BK7YM4s/qtWk096kS4bSE7W0JTf923a+0VsfnqL5+1Q+1XQVJEs2gBvnOYNUDARV2fgie1ZyLMAs6yZ1pKBp0uoFEcrPV97F2wB6JZlLJGfHIQ567ILv3/G315+ZBOg1Z5RML6xK4tqf8/WEUWoOhrgW/1vFTmvisNbEmHBTolYbXu49zucLxdFpEfd9VFbf8aSX8oirG4rMZ5RXwMdXQ+i89IB8arBVYW0738e2yMA1kaP71BZ7qvimFVahD9dqBSIRRY/UDb0lYhgLvCty3ECfdn4Dk6H8cVqg8AzvT0+SpPfDbRYR5GphY5ZbokuxmspEF+dGz1Qjq1/brkDRXOMJFCwCmv3A8ngybEauk/0T/kng8ZIQ5jzMUROf9Ge3/JwYG2CTY/4PHawvTUOTD/R0TXfGmo2LQQSxoFBemD5jTi0vfkjfCDHJiJuOJPAmhdplXp/zVgYcMlhn7QiNfjmIvKChepera/a1WY3p6RFBKVTw/FVxVEvPH2MEMYTg
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: gitops-webhook-token

