apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ibm-entitlement-key
spec:
  encryptedData:
    .dockerconfigjson: AgB0sn9d6ajdJLMcFSb8FRhXLn2RRFkmaqemXhWVI5x7m0jFBdtVssTX9bScZCVX4le6wOR1asplE83Y8DfMiiZPphsDcd1F/4Ctwf+KQOH1tfYMR0x4l/C9t/55N23yq6+aL+Q0evwVuDwP7jq5G28WSARV48o1BimRUwI9Lqyq2qwA5r0O976wn6XZo4IIkV4B0MKt7IsVeUMX/Pf5SzozIkFMvQ7m18KeR8V8VMzFEWF3YwInvCPYu5WWln83EVaAz+vZLuALJx7erKmk3sUSwI/s714U8FyOh7DMwgV7CJRonTS0yGky8vCUMdrbuLu0GG/ELKhQy7ni+U4iVJHx8hW43yAA/zSMix+ZL9WxFlLyXk4I7obJVq5Fp+fHG8EfP1auIxorp3WjUAAheLdHi3noW8LW8MUEpcwWeqFh5DUvb7oY2/NM4q5SltSNqRvo/BfeggzQ9zGivn//BYOSBU0+cvGXGWxu36YS0/b9Q7N6o+BYhb3MFjDLSxuu++n9PqQIkX4eHMJR07mpanTPJomL2OnUL0x3vLrjzV6UNoLXdsG21fOnel9cvF8fuLkujrF4ThRdRHBFTc+JY/n2papzbitpVZRvzLv0CtVkD3j1K2ha9ENF4qOQpnV+djpr43X0FgQa+ABopTSh1KS/fMyDefzmd/Z8indHveH58qCA1PWk9KF5U+5d+7OqwgCh6gknooa9HbEA8nj4o2KKn8OfVU9suzEkIQ98Lecql8svTLgdrqTQpLEitnboTP+4Ol+p8pR5zYnT1HzR6OpRUweBW+zIjo6PONWvrNGjOZFDCEG5F0IpG5rJAWShTqX0pEAbQSMaTONU+apmzWS6B4PJb13YCyIeLLAc2oIjE9bsHy7I47pLMgkXGtRKWA4L9dukowLmiHKpW6NgsFcZxKKX7sjRNJgLX69WpYqBkcYnvB/1vRE3EZ/zDTSKNoMYIEI6JbHXI+lTRqceU9Qf03zuEIgMyn6XFMsd33VXuwQnvR6MgGmp4mqqTWlbI7xvX0DBodIhatjKYX2AEOj9yUVdg1pSZoTR2VptD8H2gpsFB2nHXMEI5MUwbs1HSxIz/4e5vZ8Gky2/q1SRbTnPX/PpUl5sk6LzRSYgaFSKqutnZrAIXVKX6Rk0vBq8qsCePMS6ZYXhROuvfgX50xtcrpTD99Ekyh2lbfIrbniLBuk8BWY6AJVRGf5UKNRUc8aJgSiyNMTp7+RX+lN5LUyV587KXyASwNLQz2+rif4QkFF2bDI7HZP3Qrffmly2U4BDtP0jFb6qAmSrguUFR3JjP4S6kdjed5W3irZve+nlz/iHZdNzFu6jboe4mmEsVK1EeeCXLhJKgCjmM8NqbVRw3uVXOnlA8DHeegFh6O7yqjUqRDUR
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: ibm-entitlement-key
    type: kubernetes.io/dockerconfigjson

