apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ace-integration-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
