apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ace-integration-server-new
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
